In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print("All libraries working")

All libraries working


In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print("All libraries working")


All libraries working


In [3]:
import numpy as np
import pandas as pd|
import matplotlib.pyplot as plt
print("All libraries working")

All libraries working


In [6]:
import numpy as np
arr=np.array([1,2,3])

In [5]:
np.array([1,2,3])


array([1, 2, 3])

In [7]:
arr.ndim

1

In [8]:
arr=np.array(34)
arr.ndim

0

In [10]:
a=np.array([[[[]]]])
a.ndim

4

In [16]:
range= np.arange(1 ,10 , 2) #start , stop , jump

In [13]:
range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
range1= np.arange(1 ,10 , 2) #start , stop , jump
range1

array([1, 3, 5, 7, 9])

In [19]:
arr = np.linspace(0,1,15)
arr

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

In [20]:
k=np.logspace(1,3,3) #logarithmic scale array->10^1->10^3 ... 3 points
k

array([  10.,  100., 1000.])

In [21]:
a=np.zeros(5) #array full of zeros
a

array([0., 0., 0., 0., 0.])

In [23]:
k=np.zeros([2,3])
k

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
arr=np.ones([4,2])
arr1=np.ones([4,2],dtype=int)
arr
arr1

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [27]:
arr=np.full(10,2)#create ana array of any full value
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [29]:
arr=np.full([2,4],7)
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [31]:
arr=np.empty([2,3])#unintualized value
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
k=np.random.rand(10) #generate random floats from (0,1)
k

array([0.26907828, 0.02917211, 0.08780685, 0.41000591, 0.06635481,
       0.73503361, 0.09555669, 0.80792745, 0.72766735, 0.78570602])

In [35]:
k=np.random.randn(2,3)#random floats standard normal distribution,mean is always=0 and standatrd deviation is aeays 1
k


array([[-0.49699698, -0.00863901, -1.37770413],
       [ 1.06263416,  0.64130378,  0.15672787]])

In [36]:
arr=np.random.randint(10,100)#random integer
arr

94

In [4]:
arr=np.random.randint(10,100,size=(2,3))
arr

array([[65, 51, 14],
       [62, 35, 12]], dtype=int32)

In [12]:
arr = np.array([1,2,3,4,5])
arr


array([1, 2, 3, 4, 5])

In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [13]:
arr.dtype


dtype('int64')

In [15]:
arr=np.array([1,2,3.6,4,5.6], dtype=np.int64)
arr

array([1, 2, 3, 4, 5])

In [16]:
#typecasting ->astype()
arr=np.array([1,2,3])
arr.dtype

dtype('int64')

In [18]:
new_arr=arr.astype(np.float64)
new_arr

array([1., 2., 3.])

In [19]:
#typecasting error
arr=np.array(['1','2','hello'])
arr2=arr.astype(np.int64)
arr2


ValueError: invalid literal for int() with base 10: np.str_('hello')

In [20]:
#reshape
arr=np.array([1,2,3,4,5,6])
reshape=arr.reshape(2,3)
print(reshape)

[[1 2 3]
 [4 5 6]]


In [21]:
reshape2=arr.reshape(3,2)
reshape2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
#ravel convert into 1d array
ravel=reshape2.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [23]:
ravel[0]=100
ravel
reshape2

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [24]:
flat=reshape2.flatten()
flat

array([100,   2,   3,   4,   5,   6])

In [25]:
flat[2]=111
reshape2

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [26]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [27]:
print(a-b)

[-3 -3 -3]


In [28]:
print(b-a)

[3 3 3]


In [29]:
print(a/b)

[0.25 0.4  0.5 ]


In [31]:
arr=np.array([1,4,6,9,16])
print(np.sqrt(arr))

[1.         2.         2.44948974 3.         4.        ]


In [32]:
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [33]:
#sine function
ang=np.array([0,np.pi,np.pi/2])
np.sin(ang)

array([0.0000000e+00, 1.2246468e-16, 1.0000000e+00])

In [35]:
a=[1,2,3,4,5]
a[-1:-4:-1]

[5, 4, 3]

In [36]:
arr=np.array([10,20,30,40,50])
#index=0,2,4
arr[::2]

array([10, 30, 50])

In [37]:
print(arr[-1])

50


In [39]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
matrix[1:3,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [41]:
#np.take built in function to perform indexng and slicing
arr=np.array([10,20,30,40,50])
ind=[0,2]
print(np.take(arr,ind))

[10 30]


In [43]:
arr=np.array([[1,2],[3,4]])
for x in np.nditer(arr):
    print(x,end=" ")

1 2 3 4 

In [45]:
#ndenumerator()
for ind,x in np.ndenumerate(arr):
    print(ind,x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [46]:
#viewws and copy
arr=np.array([1,2,3,4,5])
view=arr[1:3]
view

array([2, 3])

In [49]:
 view[0]=200
 view

array([200,   3])

In [50]:
arr


array([  1, 200,   3,   4,   5])

In [54]:
arr=np.array([1,23,3,4,5,6,7,8,9])
copy=arr[1:3].copy()
copy[0]=2
copy

array([2, 3])

In [55]:
arr

array([ 1, 23,  3,  4,  5,  6,  7,  8,  9])

In [56]:
arr=np.array([[1,2],[6,7]])
arr.transpose()

array([[1, 6],
       [2, 7]])

In [62]:
arr=np.array([[1,2],[6,7]])
arr.shape

(2, 2)

In [61]:

swap=np.swapaxes(arr,0,1)
swap.shape

(2, 2)

In [63]:
a=np.array([1,2])
b=np.array([3,4])
combine=np.concatenate((a,b))
combine

array([1, 2, 3, 4])

In [65]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[6,7]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [66]:
np.hstack((a,b))

array([[1, 2, 4, 5],
       [3, 4, 6, 7]])

In [67]:
np.stack((a,b),axis=0)

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

In [69]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[6,7]])
np.stack((a,b),axis=1)

array([[[1, 2],
        [4, 5]],

       [[3, 4],
        [6, 7]]])

In [70]:
a=np.array([[1,2],[3,4],[5,6],[7,8]])
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [71]:
np.split(a,2)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [72]:
np.split(a,4)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]

In [73]:
arr=np.array([1,2,3])
print(np.repeat(arr,2))

[1 1 2 2 3 3]


In [74]:
np.tile(arr,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [75]:
arr=np.array([1,2,3])
np.sum(arr)

np.int64(6)

In [76]:
np.mean(arr)

np.float64(2.0)

In [77]:
np.median(arr)

np.float64(2.0)

In [78]:
np.std(arr)

np.float64(0.816496580927726)

In [79]:
np.var(arr)

np.float64(0.6666666666666666)

In [82]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
np.sum(matrix,axis=1)

array([ 6, 15, 24])

In [84]:
np.sum(matrix,axis=0)

array([12, 15, 18])

In [85]:
#cumulatative operations
np.cumsum(arr)

array([1, 3, 6])

In [87]:
np.cumprod(arr)

array([1, 2, 6])

In [88]:
#where
result=np.where(arr < 2,"low","high")
result

array(['low', 'high', 'high'], dtype='<U4')

In [89]:
arr

array([1, 2, 3])

In [90]:
result=np.where(arr < 2,"low","high")
result

array(['low', 'high', 'high'], dtype='<U4')

In [92]:
#conditional
np.argwhere(arr > 0)

array([[0],
       [1],
       [2]])

In [94]:
arr=np.array([10,20,30,40,705])
mask=np.logical_and(arr >15 ,arr < 35)
mask

array([False,  True,  True, False, False])

In [95]:
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
np.argwhere(matrix > 5)

array([[1, 2],
       [2, 0],
       [2, 1],
       [2, 2]])

In [97]:
arr

array([ 10,  20,  30,  40, 705])

In [100]:
mask=np.logical_and(arr > 3,arr < 26)
arr[mask]

array([10, 20])

In [103]:
#Broadcasting
image=np.array([[200,150],[100,250]])
image

array([[200, 150],
       [100, 250]])

In [104]:
brightness=image+50
brightness

array([[250, 200],
       [150, 300]])

In [127]:
#vectoriztion
def square(x):
    return x*x

folk=np.vectorize(square)

array([ 10,  20,  30,  40, 705])

In [128]:
folk(arr)

array([   100,    400,    900,   1600, 497025])

In [129]:
a=np.array([1,2,np.nan,4])
a

array([ 1.,  2., nan,  4.])

In [5]:
np.__version__



'2.3.5'

##Create & Read

#### 1D array

In [8]:
arr1=np.array([1,2,3,4,5,6,7])
arr1

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
arr1.shape

(7,)

In [11]:
arr1.dtype

dtype('int64')

In [13]:
arr1.size

7

In [14]:
arr2=np.array([[1,2],[3,4]])

In [15]:
arr2

array([[1, 2],
       [3, 4]])

In [17]:
arr2.ndim


2

In [18]:
arr2.shape

(2, 2)

In [19]:
arr2.dtype

dtype('int64')

In [20]:
arr3=np.array([[[1,2,3],[4,5,6]],[[11,12,31],[41,51,61]],[[11,12,13],[14,15,16]]])

In [21]:
arr3


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 31],
        [41, 51, 61]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [22]:
arr3.ndim

3

In [24]:
arr3.shape

(3, 2, 3)

###CREATE RANDOM ARRAY

In [25]:
random=np.random.rand(3,2,3)

In [26]:
random

array([[[0.26382185, 0.96066029, 0.80458943],
        [0.34814996, 0.22886619, 0.11885977]],

       [[0.12276119, 0.37598491, 0.16251345],
        [0.30091499, 0.11825743, 0.52300341]],

       [[0.67987285, 0.58322983, 0.00660005],
        [0.17822837, 0.7229279 , 0.53439892]]])

In [28]:
random.dtype

dtype('float64')

In [30]:
zeros=np.zeros((3,2,3))

In [31]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [32]:
zeros.ndim

3

In [36]:
full=np.full((3,2,3),2)
full

array([[[2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2]]])

In [38]:
ones=np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [40]:
arr3[0:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 31],
        [41, 51, 61]]])

##UPDATING AND DELETING 

In [43]:
a1=np.random.rand(2,3,2)
a2=np.random.rand(2,3,2)

In [44]:
a1


array([[[0.76425038, 0.64346586],
        [0.47008042, 0.90644955],
        [0.2438619 , 0.18076227]],

       [[0.30780273, 0.9227907 ],
        [0.70301393, 0.78369643],
        [0.83747236, 0.17713079]]])

In [47]:
a2


array([[[0.33521198, 0.5866845 ],
        [0.86409309, 0.43521499],
        [0.62313965, 0.91896283]],

       [[0.96277484, 0.53324202],
        [0.26873031, 0.12713487],
        [0.65705547, 0.39537281]]])

## BASIC MATH OPERATION

In [49]:
np.add(a1,a2)

array([[[1.09946236, 1.23015036],
        [1.33417351, 1.34166454],
        [0.86700155, 1.0997251 ]],

       [[1.27057757, 1.45603272],
        [0.97174424, 0.91083129],
        [1.49452783, 0.57250359]]])

In [50]:
np.subtract(a2,a1)

array([[[-0.4290384 , -0.05678136],
        [ 0.39401268, -0.47123456],
        [ 0.37927775,  0.73820056]],

       [[ 0.6549721 , -0.38954868],
        [-0.43428361, -0.65656156],
        [-0.18041688,  0.21824202]]])

## STATICAL FUNCTION

In [51]:
sqrt=np.sqrt(23)
abs=np.abs(-12)
power=np.power(2,8)
log=np.log(25)
mins=np.min(a1)
maxs=np.max(a2)

In [52]:
sqrt

np.float64(4.795831523312719)

In [53]:
abs

np.int64(12)

In [54]:
power

np.int64(256)

In [55]:
log

np.float64(3.2188758248682006)

In [56]:
mins

np.float64(0.17713078730562548)

In [57]:
maxs

np.float64(0.9627748373828112)

## UPDATE

In [58]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 31],
        [41, 51, 61]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [59]:
arr3[0][0][2]=500

In [60]:
arr3

array([[[  1,   2, 500],
        [  4,   5,   6]],

       [[ 11,  12,  31],
        [ 41,  51,  61]],

       [[ 11,  12,  13],
        [ 14,  15,  16]]])

In [61]:
arr3.sort()

In [62]:
arr3

array([[[  1,   2, 500],
        [  4,   5,   6]],

       [[ 11,  12,  31],
        [ 41,  51,  61]],

       [[ 11,  12,  13],
        [ 14,  15,  16]]])

In [63]:
arr3=arr3.reshape((2,3,3))

In [64]:
arr3

array([[[  1,   2, 500],
        [  4,   5,   6],
        [ 11,  12,  31]],

       [[ 41,  51,  61],
        [ 11,  12,  13],
        [ 14,  15,  16]]])

## APPENDING AND INSERTING

In [65]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [66]:
new_array=np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [69]:
append=np.append(zeros,new_array,axis=1)
append

array([[[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]])

# INSERT

In [70]:
insert_array=np.insert(zeros,1,new_array,axis=0)

In [71]:
insert_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

# SAVE AND DELETE 

In [74]:
arr4=np.random.rand(3,2,3)
arr4

array([[[0.90801306, 0.90831054, 0.93849793],
        [0.45337087, 0.61821451, 0.29983861]],

       [[0.84870594, 0.18518224, 0.28280702],
        [0.22867541, 0.65914995, 0.2254814 ]],

       [[0.51777102, 0.89674498, 0.0465207 ],
        [0.75441991, 0.07446979, 0.3900295 ]]])

In [79]:
arr5=np.delete(arr4,0,axis=1)

In [80]:
np.save('new_array',arr5)

In [81]:
np.load('new_array.npy')

array([[[0.45337087, 0.61821451, 0.29983861]],

       [[0.22867541, 0.65914995, 0.2254814 ]],

       [[0.75441991, 0.07446979, 0.3900295 ]]])